/**
 * Words for Art Keys: short, concrete, easy to say aloud and to write down.
 * Nothing here can describe a person, so a key never becomes an identity.
 */
export const KEY_WORDS: string[] = [
  'MOON','WHALE','KITE','EMBER','RIVER','CEDAR','ORBIT','PRISM','HARBOR','THISTLE',
  'LANTERN','MARBLE','COMET','FERN','GLACIER','HOLLOW','IVORY','JASPER','KELP','LUMEN',
  'MEADOW','NEBULA','ONYX','PEBBLE','QUARTZ','RIPPLE','SABLE','TIDE','UMBER','VELVET',
  'WILLOW','XENON','YARROW','ZEPHYR','ANCHOR','BASIN','CINDER','DUSK','ECHO','FALCON',
  'GROTTO','HEATHER','INDIGO','JUNIPER','KESTREL','LICHEN','MANTLE','NOMAD','OTTER','PLUME',
  'QUILL','RAVEN','SPIRE','TALON','URCHIN','VAPOR','WREN','XYLEM','YONDER','ZENITH',
  'ALCOVE','BRAMBLE','CANOPY','DELTA','EMBERS','FJORD','GARNET','HALO','ISLET','JETTY',
  'KNOLL','LAGOON','MESA','NECTAR','OASIS','PRAIRIE','QUAY','REEF','SUMMIT','TUNDRA',
  'UPLAND','VALLEY','WHARF','YIELD','ZINC','AMBER','BIRCH','COBALT','DUNE','ELDER',
  'FLINT','GINGER','HAZEL','IRIS','JADE','KRILL','LARCH','MAPLE','NUTMEG','OLIVE',
  'POPPY','QUINCE','ROWAN','SORREL','TANSY','UMBRA','VIOLET','WALNUT','YEW','ZEBRA',
  'ARROW','BEACON','CANDLE','DRIFT','EASEL','FEATHER','GLIMMER','HUSH','INKWELL','JOURNEY',
  'KINDLE','LULLABY','MIRROR','NOTION','OPAL','PARADE','QUIVER','RIBBON','SHIMMER','TEMPO',
  'UNISON','VESSEL','WHISPER','YARN','ZODIAC','ATLAS','BUTTON','CANVAS','DOMINO','ENVELOPE',
  'FIDDLE','GARLAND','HAMMOCK','IGLOO','JIGSAW','KETTLE','LADDER','MITTEN','NEEDLE','ORIGAMI',
  'PUZZLE','QUILT','RATTLE','SATCHEL','TEAPOT','UKULELE','VIOLIN','WAGON','YOYO','ZIPPER',
  'ACORN','BADGER','CRANE','DOLPHIN','EAGLE','FINCH','GECKO','HERON','IBIS','JACKAL',
  'KOALA','LEMUR','MAGPIE','NARWHAL','OCELOT','PUFFIN','QUAIL','ROBIN','SALMON','TAPIR',
  'URIAL','VIPER','WALRUS','YAKS','ZORSE','APRICOT','BASIL','CLOVER','DAMSON','ENDIVE',
  'FIGTREE','GOURD','HONEY','ISATIS','JASMINE','KUMQUAT','LOTUS','MANGO','NETTLE','ORCHID',
  'PEONY','QUINOA','RADISH','SAFFRON','TULIP','UMBEL','VANILLA','WHEAT','YUCCA','ZINNIA',
  'BREEZE','CLOUD','DRIZZLE','EQUINOX','FROST','GALE','HAZE','ICICLE','JETSTREAM','KELVIN',
  'LIGHTNING','MONSOON','NIMBUS','OVERCAST','PRESSURE','QUAKE','RAINBOW','SOLSTICE','THUNDER','UPDRAFT',
  'VORTEX','WINDOW','YEARLING','ZEPHYRS','BALLAD','CHORUS','DUET','ETUDE','FUGUE','GAMUT',
  'HARMONY','INTERVAL','JAZZ','KEYNOTE','LYRIC','MELODY','NOCTURNE','OCTAVE','PRELUDE','QUARTET',
  'RHYTHM','SONATA','TREBLE','UNDERTONE','VERSE','WALTZ','YODEL','ZITHER','BRIDGE','COMPASS',
  'DIAL','ENGINE','FERRY','GONDOLA','HELM','ISLAND','JUNCTION','KEEL','LIGHTHOUSE','MARINA',
  'NORTH','OUTPOST','PIER','QUEST','ROUTE','SIGNAL','TRAIL','UNDERTOW','VOYAGE','WANDER',
  'ANVIL','BELLOWS','CHISEL','DOWEL','ETCHING','FURNACE','GLAZE','HANDLE','INLAY','JOINERY',
  'KILN','LATHE','MORTAR','NAIL','OCHRE','PIGMENT','QUARRY','RESIN','SOLDER','TIMBER'
];

if (new Set(KEY_WORDS).size !== KEY_WORDS.length) {
  throw new Error('Art Key wordlist contains duplicates');
}
